list.Set( "SCarEngineSounds", "#Mafia Bolt Ace 1", { carsound_enginesound = "mafia/fordT_NPC.wav" } )
list.Set( "SCarEngineSounds", "#Mafia Bolt Ace 2", { carsound_enginesound = "mafia/fordT1_NPC.wav" } )
list.Set( "SCarEngineSounds", "#Mafia Bolt Model B 1", { carsound_enginesound = "mafia/fordA_NPC.wav" } )
list.Set( "SCarEngineSounds", "#Mafia Bolt Model B 2", { carsound_enginesound = "mafia/fordA1_NPC.wav" } )
list.Set( "SCarEngineSounds", "#Mafia Bolt V8", { carsound_enginesound = "mafia/fordV8_NPC.wav" } )
list.Set( "SCarEngineSounds", "#Mafia Bolt V8 2", { carsound_enginesound = "mafia/fordV8_0.wav" } )
list.Set( "SCarEngineSounds", "#Mafia Bolt V8 3", { carsound_enginesound = "mafia/fordV8_2.wav" } )
